# https://devblogs.microsoft.com/visualstudio/web-api-development-in-visual-studio-2022/

@CleanArchitecture.Application_HostAddress = https://localhost:7109

Get {{CleanArchitecture.Application_HostAddress}}/customers

###

Post {{CleanArchitecture.Application_HostAddress}}/customers
Content-Type: application/json

{
  "name": "Dan"
}

###

@Customer_Id = f1ec6be7-2079-4804-9e8d-0db9b30465ac
Get {{CleanArchitecture.Application_HostAddress}}/customers/{{Customer_Id}}

###

@Customer_Id = 2c6a940d-3f6c-418e-8cdb-cae24163baef
Delete {{CleanArchitecture.Application_HostAddress}}/customers/{{Customer_Id}}

###

@Customer_Id = 2c6a940d-3f6c-418e-8cdb-cae24163baef
Put {{CleanArchitecture.Application_HostAddress}}/customers/{{Customer_Id}}
Content-Type: application/json

{
  "name": "Andrew"
}